# Generated by Django 6.0.3 on 2026-03-22 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoclog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.product'),
        ),
    ]
