# Generated by Django 6.0.3 on 2026-03-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0004_sale_saleitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='product',
        ),
        migrations.AddField(
            model_name='stoclog',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Plastik'), ('debt', 'Nasiya'), ('none', 'Noma’lum/Ombor')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='stoclog',
            name='price_at_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stoclog',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='SaleItem',
        ),
    ]
